### ISSUE TITLE
Returns wrong/previous image when only changing the imageId param

### ISSUE THREAD

**Issue by chiefnoah** [dxprog/reddit-booru#12]
When the only change between request is the `imageId` parameter, it returns a previous image.

[Image 1](http://redditbooru.com/images/?limit=1&imageId=1210337) -> [Image 2](http://redditbooru.com/images/?limit=1&imageId=1210272) will return the same thing when they shouldn't. I'm guessing cache issue? Maybe?

**Comment by dxprog** [comment]
Fixed in commit 0bdac43
