### ISSUE TITLE
[Feature] Select all in subreddit selection dropdown

### ISSUE THREAD

**Issue by alphachung** [dxprog/reddit-booru#15]
Because checking 27 checkboxes within that few seconds that the page won't reload require some mouse acrobatics. Although I am able to pull it off, a select all button would be handy. 

![newconcept](https://cloud.githubusercontent.com/assets/5276387/10716293/d5e4ee1c-7b6e-11e5-9041-7ff989cc520b.png)

**Comment by dxprog** [comment]
Resolved in commit cd94523
