### ISSUE TITLE
Screensaver ignores "show NSFW"

### ISSUE THREAD

**Issue by pitman10** [dxprog/reddit-booru#28]
I had "Show NSFW" off and the Screensaver still showed NSFW pictures to me.  

It should respect the setting.

**Comment by dxprog** [comment]
Yep, the viewer doesn't respect the setting. Been trying to figure out what the experience is when that's checked. Also, NSFW is broken entirely in IE/Edge which should probably be addressed as well.

**Comment by alphachung** [comment]
https://stackoverflow.com/questions/25850100/css-blur-in-ie-11

**Comment by dxprog** [comment]
Yeah, I've been around the block with this one. IE is just going to get "NSFW" text or the old image from RBv1. If Firefox doesn't get nice things, then neither does IE/Edge.

**Comment by alphachung** [comment]
What Firefox doesn't support currently? Also, if Firefox + Edge are not going to get support then RB is going to be WebKit/Blink only :confused:

**Comment by dxprog** [comment]
Firefox and IE are supported, but they won't get some visual flair.

**Comment by dxprog** [comment]
Checkbox is now honored in viewer/screensaver mode. Verified working in Chrome, FF, and Edge.
