### ISSUE TITLE
My first experience with a false positive (Search algorithm)

### ISSUE THREAD

**Issue by whung1** [dxprog/reddit-booru#29]
Given the following search...

http://redditbooru.com/search/?imageUri=http%3A%2F%2Fi2.pixiv.net%2Fimg-original%2Fimg%2F2015%2F12%2F01%2F16%2F53%2F14%2F53832513_p0.jpg

Doesn't seem that the reverse search algorithm often hits false positives in matching, so thought it was noteworthy in case of future refinement. Can close if its not necessary to be here.

**Comment by mikairi** [comment]
Not sure what the problem is here.. This is how it showed up for me
![image](https://cloud.githubusercontent.com/assets/678340/11547947/eb2e42d0-9925-11e5-848e-0f86e776a5a1.png)

Did you mean you did not see the first image there?

**Comment by whung1** [comment]
Realized I just got rid of the evidence by posting it. Before it was running a false positive BEFORE I posted that image.

My bad, I'll just close it for now.

**Comment by dxprog** [comment]
You're the first (reported) false positive in 3 years running on this algo! I'm actually in the process of working up something new that I hope will be more accurate, but I'm not entirely certain it won't have more false positives. In the end, I don't think this is a bug as it's very difficult to dial in what the threshold for "this is a duplicate" is the way things are now. It's for that reason that the previews on the side are displayed.
