### ISSUE TITLE
Drag and Drop doesn't give options anymore

### ISSUE THREAD

**Issue by pitman10** [dxprog/reddit-booru#32]
Previously when I dragged an image file from my PC to redditbooru's main page it gave me an option to either "Search" or "Upload" and now that's gone, was this intentional ?

**Comment by dxprog** [comment]
Firefox?

**Comment by pitman10** [comment]
Yes.

**Comment by dxprog** [comment]
This one actually affected all browsers. Not sure of what the cause is entirely, but currently looks like a backbone issue (or I'm using it wrong). Either way, I have a patch in place that unbreaks it.
