### ISSUE TITLE
Many sources breaks pagination (memcache key size limit)

### ISSUE THREAD

**Issue by AllenJB** [dxprog/reddit-booru#38]
If a large number of sources are configured, pagination breaks because memcache (and in particular [the pecl-memcache implementation](http://git.php.net/?p=pecl%2Fcaching%2Fmemcache.git&a=search&h=HEAD&st=grep&s=KEY_MAX)) has a key size limit of 250 characters. When a key exceeds this length it is silently truncated by pecl-memcache, which causes, in particular, first the timestamp then eventually the list of sources to be truncated.

A possible solution might be to use a hash of the current key.

For reference I'm experiencing this issue with about 75 sources configured, but depending on the source ids and the other parameters the problems might start occurring with less than that.

**Comment by dxprog** [comment]
Fixed in 079d301. I used to hash keys all the time (mostly for obfuscation). Not sure when I quit... Good to know about the key length, though. Would've hit that myself eventually.
