### ISSUE TITLE
Filter dropdown might not fit in viewport

### ISSUE THREAD

**Issue by alphachung** [dxprog/reddit-booru#49]
Because of the increasing amount of subreddits RB supports, the filter dropdown is now so big that the checkboxes cannot all fit inside the screen that I use, but there is no way to scroll down the list.

I'm using a 13" MacBook Pro and using the browser that takes up the least amount of vertical space for controls (Safari) and maximum window height: 
<img width="1507" alt="ae106d44-f747-4186-9170-cb60472aed8b" src="https://user-images.githubusercontent.com/5276387/52363706-472eb500-2a7e-11e9-9d29-4125e6bc9302.png">

I normally use Chrome, and because the controls takes up more vertical space thus reducing the page height, the refresh button is inaccessible for me most of the time.

I'd suggest redesigning the dropdown, or reducing the font size.

**Comment by dxprog** [comment]
Yeah, there's some light conversation about redesigning the nav/dropdown over on the [subreddit](https://www.reddit.com/r/redditbooru/comments/a8fwpp/upcoming_survey_and_just_general_thoughts_about/). In the meantime, I've made the dropdown full width and reduced the column size. On my 1280px wide screen, it's all fitting correctly now, though I want to test on my larger monitors before I deploy (probably Sunday).

Thanks for the report!

**Comment by dxprog** [comment]
Deployed and verified on multiple screen sizes.
